/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.sablecc.codegeneration.java.macro;

public class MFalseGroup {

    MFalseGroup() {

    }

    @Override
    public String toString() {

        StringBuilder sb = new StringBuilder();
        sb.append("false");
        return sb.toString();
    }

}
