/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.sablecc.codegeneration.java.macro;

public class MNodeAlternativeParent {

    MNodeAlternativeParent() {

    }

    @Override
    public String toString() {

        StringBuilder sb = new StringBuilder();
        sb.append("    extends Node {");
        sb.append(System.getProperty("line.separator"));
        return sb.toString();
    }

}
