/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.sablecc.codegeneration.java.macro;

public class MPublicConstructor {

    MPublicConstructor() {

    }

    @Override
    public String toString() {

        StringBuilder sb = new StringBuilder();
        sb.append("public ");
        return sb.toString();
    }

}
