/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.objectmacro.codegeneration.java.macro;

public class MContextName extends Macro{

    private String field_ListContextName;

    public MContextName(String pListContextName){

        this.setPListContextName(pListContextName);
    }

    private void setPListContextName(String pListContextName){
        if(pListContextName == null){
            throw ObjectMacroException.parameterNull("ListContextName");
        }

        this.field_ListContextName = pListContextName;
    }

    private String buildListContextName(){

        return this.field_ListContextName;
    }

    private String getListContextName(){

        return this.field_ListContextName;
    }

    @Override
    void apply(
            InternalsInitializer internalsInitializer){

        internalsInitializer.setContextName(this);
    }

    @Override
    public String build(){

        String local_expansion = this.expansion;

        if(local_expansion != null){
            return local_expansion;
        }

        StringBuilder sb0 = new StringBuilder();

        sb0.append(buildListContextName());

        local_expansion = sb0.toString();
        this.expansion = local_expansion;
        return local_expansion;
    }

    @Override
    String build(Context context) {
        return build();
    }
}
