/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.objectmacro.codegeneration.java.macro;

public class MDirectiveFields {

  private final String pParamName;
  private final MDirectiveFields mDirectiveFields = this;

  public MDirectiveFields(String pParamName) {
    if(pParamName == null) throw new NullPointerException();
    this.pParamName = pParamName;
  }

  String pParamName() {
    return this.pParamName;
  }

  private String rParamName() {
    return this.mDirectiveFields.pParamName();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("    private DSeparator ");
    sb.append(rParamName());
    sb.append("Separator;");
    sb.append(System.getProperty("line.separator"));
    sb.append(System.getProperty("line.separator"));
    sb.append("    private DBeforeFirst ");
    sb.append(rParamName());
    sb.append("BeforeFirst;");
    sb.append(System.getProperty("line.separator"));
    sb.append(System.getProperty("line.separator"));
    sb.append("    private DAfterLast ");
    sb.append(rParamName());
    sb.append("AfterLast;");
    sb.append(System.getProperty("line.separator"));
    sb.append(System.getProperty("line.separator"));
    sb.append("    private DNone ");
    sb.append(rParamName());
    sb.append("None;");
    sb.append(System.getProperty("line.separator"));
    return sb.toString();
  }

}
