/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.objectmacro.codegeneration.java.macro;

public class MInitDirectives extends Macro{

    private String field_ParamName;

    private Macro list_NewDirective[];

    private final Context NewDirectiveContext = new Context();

    public MInitDirectives(String pParamName, Macro pNewDirective[]){

        this.setPParamName(pParamName);
        this.setPNewDirective(pNewDirective);
    }

    private void setPParamName(String pParamName){
        if(pParamName == null){
            throw ObjectMacroException.parameterNull("ParamName");
        }

        this.field_ParamName = pParamName;
    }

    private void setPNewDirective(Macro pNewDirective[]){
        if(pNewDirective == null){
            throw ObjectMacroException.parameterNull("NewDirective");
        }

        Macro macros[] = pNewDirective;
        this.list_NewDirective = new Macro[macros.length];
        int i = 0;

        for(Macro macro : macros){
            if(macro == null){
                throw ObjectMacroException.macroNull(i, "NewDirective");
            }

            macro.apply(new InternalsInitializer("NewDirective"){
@Override
void setNewDirective(MNewDirective mNewDirective){

                mNewDirective.setParamName(NewDirectiveContext, getParamName());
}
});

            this.list_NewDirective[i++] = macro;

        }
    }

    private String buildParamName(){

        return this.field_ParamName;
    }

    private String buildNewDirective(){

        StringBuilder sb0 = new StringBuilder();
        Context local_context = NewDirectiveContext;
        Macro macros[] = this.list_NewDirective;
                boolean first = true;
        int i = 0;

        for(Macro macro : macros){
                        
            sb0.append(macro.build(local_context));
            i++;

                    }

        return sb0.toString();
    }

    private String getParamName(){

        return this.field_ParamName;
    }

    private Macro[] getNewDirective(){

        return this.list_NewDirective;
    }

    @Override
    void apply(
            InternalsInitializer internalsInitializer){

        internalsInitializer.setInitDirectives(this);
    }

    @Override
    public String build(){

        String local_expansion = this.expansion;

        if(local_expansion != null){
            return local_expansion;
        }

        StringBuilder sb0 = new StringBuilder();

        sb0.append("    private void init");
        sb0.append(buildParamName());
        sb0.append("Directives()");
        sb0.append("{");
        sb0.append(LINE_SEPARATOR);
        sb0.append("        ");
        sb0.append(buildNewDirective());
        sb0.append(LINE_SEPARATOR);
        sb0.append("    }");

        local_expansion = sb0.toString();
        this.expansion = local_expansion;
        return local_expansion;
    }

    @Override
    String build(Context context) {
        return build();
    }
}
