/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.objectmacro.codegeneration.java.macro;

public class MInlineEol {

    public MInlineEol() {

    }

    @Override
    public String toString() {

        StringBuilder sb = new StringBuilder();
        sb.append("System.getProperty(\"line.separator\")");
        return sb.toString();
    }

}
