/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.objectmacro.codegeneration.java.macro;

import java.util.*;

public  class MInternalMacrosValueField extends Macro{
    
    private Map<Context, String> field_ParamName = new LinkedHashMap<>();
    
    public MInternalMacrosValueField(Macros macros){
        
        
        this.setMacros(macros);
    }
    
        void setParamName(
                Context context,
                String value) {
    
            if(value == null){
                throw new RuntimeException("value cannot be null here");
            }
    
            this.field_ParamName.put(context, value);
        }
    
    String buildParamName(Context context){
    
        return this.field_ParamName.get(context);
    }
    
    String getParamName(Context context){
    
        return this.field_ParamName.get(context);
    }
    
    
    @Override
     void apply(
             InternalsInitializer internalsInitializer){
    
         internalsInitializer.setInternalMacrosValueField(this);
     }
    
    @Override
    public String build(Context context){
    
        BuildState buildState = this.build_states.get(context);
    
        if(buildState == null){
            buildState = new BuildState();
        }
        else if(buildState.getExpansion() == null){
            throw ObjectMacroException.cyclicReference("InternalMacrosValueField");
        }
        else{
            return buildState.getExpansion();
        }
        this.build_states.put(context, buildState);
        List<String> indentations = new LinkedList<>();
        StringBuilder sbIndentation = new StringBuilder();
    
        
    
    
    
        StringBuilder sb0 = new StringBuilder();
    
        sb0.append("final InternalValue ");
        sb0.append(buildParamName(context));
        sb0.append("Value;");
    
        buildState.setExpansion(sb0.toString());
        return sb0.toString();
    }
    
    
    
    private void setMacros(Macros macros){
        if(macros == null){
            throw new InternalException("macros cannot be null");
        }
    
        this.macros = macros;
    }
}