/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.objectmacro.codegeneration.java.macro;

import java.util.*;

public class MNewDirective {

    private final String pParamName;

    private final String pDirectiveName;

    private final String pIndexBuilder;

    private final MNewDirective mNewDirective = this;

    private final List<Object> eStringPart_ParamInsertPart_EolPart_InsertMacroPart
            = new LinkedList<>();

    public MNewDirective(
            String pParamName,
            String pDirectiveName,
            String pIndexBuilder) {

        if (pParamName == null) {
            throw new NullPointerException();
        }
        this.pParamName = pParamName;
        if (pDirectiveName == null) {
            throw new NullPointerException();
        }
        this.pDirectiveName = pDirectiveName;
        if (pIndexBuilder == null) {
            throw new NullPointerException();
        }
        this.pIndexBuilder = pIndexBuilder;
    }

    public MStringPart newStringPart(
            String pString,
            String pIndexBuilder) {

        MStringPart lStringPart = new MStringPart(pString, pIndexBuilder);
        this.eStringPart_ParamInsertPart_EolPart_InsertMacroPart
                .add(lStringPart);
        return lStringPart;
    }

    public MParamInsertPart newParamInsertPart(
            String pParamName,
            String pIndexBuilder) {

        MParamInsertPart lParamInsertPart
                = new MParamInsertPart(pParamName, pIndexBuilder);
        this.eStringPart_ParamInsertPart_EolPart_InsertMacroPart
                .add(lParamInsertPart);
        return lParamInsertPart;
    }

    public MEolPart newEolPart(
            String pIndexBuilder) {

        MEolPart lEolPart = new MEolPart(pIndexBuilder);
        this.eStringPart_ParamInsertPart_EolPart_InsertMacroPart.add(lEolPart);
        return lEolPart;
    }

    public MInsertMacroPart newInsertMacroPart(
            String pName,
            String pIndexBuilder,
            String pIndexInsert) {

        MInsertMacroPart lInsertMacroPart
                = new MInsertMacroPart(pName, pIndexBuilder, pIndexInsert);
        this.eStringPart_ParamInsertPart_EolPart_InsertMacroPart
                .add(lInsertMacroPart);
        return lInsertMacroPart;
    }

    String pParamName() {

        return this.pParamName;
    }

    String pDirectiveName() {

        return this.pDirectiveName;
    }

    String pIndexBuilder() {

        return this.pIndexBuilder;
    }

    private String rIndexBuilder() {

        return this.mNewDirective.pIndexBuilder();
    }

    private String rParamName() {

        return this.mNewDirective.pParamName();
    }

    private String rDirectiveName() {

        return this.mNewDirective.pDirectiveName();
    }

    @Override
    public String toString() {

        StringBuilder sb = new StringBuilder();
        sb.append("        StringBuilder sb");
        sb.append(rIndexBuilder());
        sb.append(" = new StringBuilder();");
        sb.append(System.getProperty("line.separator"));
        for (Object oStringPart_ParamInsertPart_EolPart_InsertMacroPart : this.eStringPart_ParamInsertPart_EolPart_InsertMacroPart) {
            sb.append(oStringPart_ParamInsertPart_EolPart_InsertMacroPart
                    .toString());
        }
        sb.append("        this.");
        sb.append(rParamName());
        sb.append("Directives.add(new D");
        sb.append(rDirectiveName());
        sb.append("(sb");
        sb.append(rIndexBuilder());
        sb.append(".toString()));");
        sb.append(System.getProperty("line.separator"));
        return sb.toString();
    }

}
