/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.objectmacro.codegeneration.java.macro;

public class MParamMacroRef {

  private final String pName;
  private final MParamMacroRef mParamMacroRef = this;

  public MParamMacroRef(String pName) {
    if(pName == null) throw new NullPointerException();
    this.pName = pName;
  }

  String pName() {
    return this.pName;
  }

  private String rName() {
    return this.mParamMacroRef.pName();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("    private InternalValue get");
    sb.append(rName());
    sb.append("(){");
    sb.append(System.getProperty("line.separator"));
    sb.append("        return this.");
    sb.append(rName());
    sb.append("Value;");
    sb.append(System.getProperty("line.separator"));
    sb.append("    }");
    sb.append(System.getProperty("line.separator"));
    return sb.toString();
  }

}
