/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.objectmacro.codegeneration.java.macro;

import java.util.*;

public  class MRedefinedApplyInitializer extends Macro{
    
    private Map<Context, String> field_ClassName = new LinkedHashMap<>();
    
    MRedefinedApplyInitializer(Macros macros){
        
        
        this.setMacros(macros);
    }
    
        void setClassName(
                Context context,
                String value) {
    
            if(value == null){
                throw new RuntimeException("value cannot be null here");
            }
    
            this.field_ClassName.put(context, value);
        }
    
    String buildClassName(Context context){
    
        return this.field_ClassName.get(context);
    }
    
    String getClassName(Context context){
    
        return this.field_ClassName.get(context);
    }
    
    
    @Override
     void apply(
             InternalsInitializer internalsInitializer){
    
         internalsInitializer.setRedefinedApplyInitializer(this);
     }
    
    @Override
    public String build(Context context){
    
        CacheBuilder cache_builder = this.cacheBuilders.get(context);
    
        if(cache_builder == null){
            cache_builder = new CacheBuilder();
        }
        else if(cache_builder.getExpansion() == null){
            throw new InternalException("Cycle detection detected lately");
        }
        else{
            return cache_builder.getExpansion();
        }
        this.cacheBuilders.put(context, cache_builder);
        List<String> indentations = new LinkedList<>();
        StringBuilder sbIndentation = new StringBuilder();
    
        
    
    
    
        StringBuilder sb0 = new StringBuilder();
    
        sb0.append("@Override");
        sb0.append(LINE_SEPARATOR);
        sb0.append(" void apply(");
        sb0.append(LINE_SEPARATOR);
        sb0.append("         InternalsInitializer internalsInitializer)");
        sb0.append("{");
        sb0.append(LINE_SEPARATOR);
        sb0.append(LINE_SEPARATOR);
        sb0.append("     internalsInitializer.set");
        sb0.append(buildClassName(context));
        sb0.append("(this);");
        sb0.append(LINE_SEPARATOR);
        sb0.append(" }");
    
        cache_builder.setExpansion(sb0.toString());
        return sb0.toString();
    }
    
    
    
    private void setMacros(Macros macros){
        if(macros == null){
            throw new InternalException("macros cannot be null");
        }
    
        this.macros = macros;
    }
}