/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.objectmacro.codegeneration.java.macro;

import java.util.*;

public class MSetInternal {

  private final String pMacroName;
  private final String pParamName;
  private final String pContext;
  private final MSetInternal mSetInternal = this;
  private final List<Object> eMacroArg_StringBuilderBuild = new LinkedList<Object>();

  public MSetInternal(String pMacroName, String pParamName, String pContext) {
    if(pMacroName == null) throw new NullPointerException();
    this.pMacroName = pMacroName;
    if(pParamName == null) throw new NullPointerException();
    this.pParamName = pParamName;
    if(pContext == null) throw new NullPointerException();
    this.pContext = pContext;
  }

  public MMacroArg newMacroArg(String pName) {
    MMacroArg lMacroArg = new MMacroArg(pName);
    this.eMacroArg_StringBuilderBuild.add(lMacroArg);
    return lMacroArg;
  }

  public MStringBuilderBuild newStringBuilderBuild(String pIndexBuilder) {
    MStringBuilderBuild lStringBuilderBuild = new MStringBuilderBuild(pIndexBuilder);
    this.eMacroArg_StringBuilderBuild.add(lStringBuilderBuild);
    return lStringBuilderBuild;
  }

  String pMacroName() {
    return this.pMacroName;
  }

  String pParamName() {
    return this.pParamName;
  }

  String pContext() {
    return this.pContext;
  }

  private String rMacroName() {
    return this.mSetInternal.pMacroName();
  }

  private String rParamName() {
    return this.mSetInternal.pParamName();
  }

  private String rContext() {
    return this.mSetInternal.pContext();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("        m");
    sb.append(rMacroName());
    sb.append(".set");
    sb.append(rParamName());
    sb.append("(");
    sb.append(rContext());
    sb.append(", ");
    for(Object oMacroArg_StringBuilderBuild : this.eMacroArg_StringBuilderBuild) {
      sb.append(oMacroArg_StringBuilderBuild.toString());
    }
    sb.append(");");
    sb.append(System.getProperty("line.separator"));
    return sb.toString();
  }

}
