/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.objectmacro.codegeneration.java.macro;

import java.util.*;

public class MVersion extends Macro{
    
    private String field_DefaultCase;
    
    
    
    
    public MVersion(String pDefaultCase){
    
            this.setPDefaultCase(pDefaultCase);
    
    }
    
    
    private void setPDefaultCase( String pDefaultCase ){
        if(pDefaultCase == null){
            throw ObjectMacroException.parameterNull("DefaultCase");
        }
    
        this.field_DefaultCase = pDefaultCase;
    }
    
    
    private String buildDefaultCase(){
    
        return this.field_DefaultCase;
    }
    
    
    private String getDefaultCase(){
    
        return this.field_DefaultCase;
    }
    
    
    
    
    
    @Override
     void apply(
             InternalsInitializer internalsInitializer){
    
         internalsInitializer.setVersion(this);
     }
    
    
    @Override
    public String build(){
    
        BuildState buildState = this.build_state;
    
        if(buildState == null){
            buildState = new BuildState();
        }
        else if(buildState.getExpansion() == null){
            throw ObjectMacroException.cyclicReference("Version");
        }
        else{
            return buildState.getExpansion();
        }
        this.build_state = buildState;
        List<String> indentations = new LinkedList<>();
        StringBuilder sbIndentation = new StringBuilder();
    
        
    
    
    
        StringBuilder sb0 = new StringBuilder();
    
        sb0.append("VERSIONS.");
        sb0.append(buildDefaultCase());
    
        buildState.setExpansion(sb0.toString());
        return sb0.toString();
    }
    
    
    @Override
    String build(Context context) {
     return build();
    }
    private String applyIndent(
                            String macro,
                            String indent){

            StringBuilder sb = new StringBuilder();
            String[] lines = macro.split( "\n");

            if(lines.length > 1){
                for(int i = 0; i < lines.length; i++){
                    String line = lines[i];
                    sb.append(indent).append(line);

                    if(i < lines.length - 1){
                        sb.append(LINE_SEPARATOR);
                    }
                }
            }
            else{
                sb.append(indent).append(macro);
            }

            return sb.toString();
    }
}