/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.objectmacro.bootstrap.macro;

import java.util.LinkedList;
import java.util.List;

public class Macro_macro_class {

    // parameter declarations
    private final String param_class_name;

    private final String param_protection;

    // nested macro declarations
    private final List<Macro_parameter_declaration> macro_parameter_declaration_list = new LinkedList<Macro_parameter_declaration>();

    private final List<Macro_nested_macro_declaration> macro_nested_macro_declaration_list = new LinkedList<Macro_nested_macro_declaration>();

    private final List<Macro_constructor_first_parameter> macro_constructor_first_parameter_list = new LinkedList<Macro_constructor_first_parameter>();

    private final List<Macro_constructor_additional_parameter> macro_constructor_additional_parameter_list = new LinkedList<Macro_constructor_additional_parameter>();

    private final List<Macro_parameter_initialisation> macro_parameter_initialisation_list = new LinkedList<Macro_parameter_initialisation>();

    private final List<Macro_instruction> macro_instruction_list = new LinkedList<Macro_instruction>();

    private final List<Macro_nested_macro> macro_nested_macro_list = new LinkedList<Macro_nested_macro>();

    // constructor
    public Macro_macro_class(
            String param_class_name,
            String param_protection) {

        this.param_class_name = param_class_name;
        this.param_protection = param_protection;
    }

    // toString
    @Override
    public String toString() {

        StringBuilder sb = new StringBuilder();
        sb.append("/* This file was generated by SableCC's ObjectMacro. */");
        sb.append(System.getProperty("line.separator"));
        sb.append(System.getProperty("line.separator"));
        sb.append("package org.sablecc.objectmacro.bootstrap.macro;");
        sb.append(System.getProperty("line.separator"));
        sb.append(System.getProperty("line.separator"));
        sb.append("import java.util.*;");
        sb.append(System.getProperty("line.separator"));
        sb.append(System.getProperty("line.separator"));
        sb.append("public class Macro_");
        sb.append(this.param_class_name);
        sb.append(" {");
        sb.append(System.getProperty("line.separator"));
        sb.append(System.getProperty("line.separator"));
        sb.append("  // parameter declarations");
        sb.append(System.getProperty("line.separator"));
        for (Macro_parameter_declaration macro_parameter_declaration : this.macro_parameter_declaration_list) {
            sb.append(macro_parameter_declaration.toString());
        }
        sb.append(System.getProperty("line.separator"));
        sb.append("  // nested macro declarations");
        sb.append(System.getProperty("line.separator"));
        for (Macro_nested_macro_declaration macro_nested_macro_declaration : this.macro_nested_macro_declaration_list) {
            sb.append(macro_nested_macro_declaration.toString());
        }
        sb.append(System.getProperty("line.separator"));
        sb.append("  // constructor");
        sb.append(System.getProperty("line.separator"));
        sb.append("  ");
        sb.append(this.param_protection);
        sb.append(" Macro_");
        sb.append(this.param_class_name);
        sb.append("(");
        for (Macro_constructor_first_parameter macro_constructor_first_parameter : this.macro_constructor_first_parameter_list) {
            sb.append(macro_constructor_first_parameter.toString());
        }
        for (Macro_constructor_additional_parameter macro_constructor_additional_parameter : this.macro_constructor_additional_parameter_list) {
            sb.append(macro_constructor_additional_parameter.toString());
        }
        sb.append(") {");
        sb.append(System.getProperty("line.separator"));
        for (Macro_parameter_initialisation macro_parameter_initialisation : this.macro_parameter_initialisation_list) {
            sb.append(macro_parameter_initialisation.toString());
        }
        sb.append("  }");
        sb.append(System.getProperty("line.separator"));
        sb.append(System.getProperty("line.separator"));
        sb.append("  // toString");
        sb.append(System.getProperty("line.separator"));
        sb.append("  public String toString() {");
        sb.append(System.getProperty("line.separator"));
        sb.append("    StringBuilder sb = new StringBuilder();");
        sb.append(System.getProperty("line.separator"));
        for (Macro_instruction macro_instruction : this.macro_instruction_list) {
            sb.append(macro_instruction.toString());
        }
        sb.append("    return sb.toString();");
        sb.append(System.getProperty("line.separator"));
        sb.append("  }");
        sb.append(System.getProperty("line.separator"));
        sb.append(System.getProperty("line.separator"));
        sb.append("  // nested macros");
        sb.append(System.getProperty("line.separator"));
        for (Macro_nested_macro macro_nested_macro : this.macro_nested_macro_list) {
            sb.append(macro_nested_macro.toString());
        }
        sb.append(System.getProperty("line.separator"));
        sb.append("}");
        sb.append(System.getProperty("line.separator"));
        return sb.toString();
    }

    // nested macros
    public Macro_parameter_declaration newMacro_parameter_declaration(
            String param_param_name) {

        Macro_parameter_declaration macro_parameter_declaration = new Macro_parameter_declaration(
                param_param_name, this.param_class_name, this.param_protection);
        this.macro_parameter_declaration_list.add(macro_parameter_declaration);
        return macro_parameter_declaration;
    }

    public Macro_nested_macro_declaration newMacro_nested_macro_declaration(
            String param_nested_macro_name) {

        Macro_nested_macro_declaration macro_nested_macro_declaration = new Macro_nested_macro_declaration(
                param_nested_macro_name, this.param_class_name,
                this.param_protection);
        this.macro_nested_macro_declaration_list
                .add(macro_nested_macro_declaration);
        return macro_nested_macro_declaration;
    }

    public Macro_constructor_first_parameter newMacro_constructor_first_parameter(
            String param_param_name) {

        Macro_constructor_first_parameter macro_constructor_first_parameter = new Macro_constructor_first_parameter(
                param_param_name, this.param_class_name, this.param_protection);
        this.macro_constructor_first_parameter_list
                .add(macro_constructor_first_parameter);
        return macro_constructor_first_parameter;
    }

    public Macro_constructor_additional_parameter newMacro_constructor_additional_parameter(
            String param_param_name) {

        Macro_constructor_additional_parameter macro_constructor_additional_parameter = new Macro_constructor_additional_parameter(
                param_param_name, this.param_class_name, this.param_protection);
        this.macro_constructor_additional_parameter_list
                .add(macro_constructor_additional_parameter);
        return macro_constructor_additional_parameter;
    }

    public Macro_parameter_initialisation newMacro_parameter_initialisation(
            String param_param_name) {

        Macro_parameter_initialisation macro_parameter_initialisation = new Macro_parameter_initialisation(
                param_param_name, this.param_class_name, this.param_protection);
        this.macro_parameter_initialisation_list
                .add(macro_parameter_initialisation);
        return macro_parameter_initialisation;
    }

    public Macro_instruction newMacro_instruction() {

        Macro_instruction macro_instruction = new Macro_instruction(
                this.param_class_name, this.param_protection);
        this.macro_instruction_list.add(macro_instruction);
        return macro_instruction;
    }

    public Macro_nested_macro newMacro_nested_macro(
            String param_nested_macro_name) {

        Macro_nested_macro macro_nested_macro = new Macro_nested_macro(
                param_nested_macro_name, this.param_class_name,
                this.param_protection);
        this.macro_nested_macro_list.add(macro_nested_macro);
        return macro_nested_macro;
    }

}
