/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.sablecc.errormessage;

public class MParserSpuriousPriority {

    private final String pName;

    private final String pLine;

    private final String pChar;

    private final MParserSpuriousPriority mParserSpuriousPriority = this;

    public MParserSpuriousPriority(
            String pName,
            String pLine,
            String pChar) {

        if (pName == null) {
            throw new NullPointerException();
        }
        this.pName = pName;
        if (pLine == null) {
            throw new NullPointerException();
        }
        this.pLine = pLine;
        if (pChar == null) {
            throw new NullPointerException();
        }
        this.pChar = pChar;
    }

    String pName() {

        return this.pName;
    }

    String pLine() {

        return this.pLine;
    }

    String pChar() {

        return this.pChar;
    }

    private String rLine() {

        return this.mParserSpuriousPriority.pLine();
    }

    private String rChar() {

        return this.mParserSpuriousPriority.pChar();
    }

    private String rName() {

        return this.mParserSpuriousPriority.pName();
    }

    @Override
    public String toString() {

        StringBuilder sb = new StringBuilder();
        sb.append(new MSemanticErrorHead().toString());
        sb.append(System.getProperty("line.separator"));
        sb.append("Line: ");
        sb.append(rLine());
        sb.append(System.getProperty("line.separator"));
        sb.append("Char: ");
        sb.append(rChar());
        sb.append(System.getProperty("line.separator"));
        sb.append("The priority of \"");
        sb.append(rName());
        sb.append("\" is already set.");
        sb.append(System.getProperty("line.separator"));
        return sb.toString();
    }

}
