/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.objectmacro.macro;

public class M_add_to_expand
        extends Macro {

    // ---- EOL ----
    private static final String EOL = System.getProperty("line.separator");

    // ---- parameters ----
    private final String p_expand_name;

    // ---- text blocks ----

    // ---- expands ----

    // ---- parent ----
    private final Macro parent;

    @Override
    public Macro get_parent() {

        return this.parent;
    }

    // ---- constructor ----
    M_add_to_expand(
            Macro parent,
            String p_expand_name) {

        this.parent = parent;
        this.p_expand_name = p_expand_name;
    }

    // ---- local parameter accessors ----

    String get_local_p_expand_name() {

        return this.p_expand_name;
    }

    // ---- local text block accessors ----

    // ---- parameter accessors ----

    private String cached_p_expand_name;

    String get_p_expand_name() {

        String result = this.cached_p_expand_name;
        if (result == null) {
            Macro current = this;
            while (!(current instanceof M_add_to_expand)) {
                current = current.get_parent();
            }
            result = ((M_add_to_expand) current).get_local_p_expand_name();
            this.cached_p_expand_name = result;
        }
        return result;
    }

    // ---- text block accessors ----

    // sub-macro creators

    // ---- append ----

    @Override
    public void appendTo(
            StringBuilder sb) {

        sb.append("    e_");
        sb.append(get_p_expand_name());
        sb.append(".add(result);");
        sb.append(EOL);
    }
}
