/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.objectmacro.macro;

public class M_expand_append_before_first_text_block
        extends Macro {

    // ---- EOL ----
    private static final String EOL = System.getProperty("line.separator");

    // ---- parameters ----
    private final String p_text_block_name;

    // ---- text blocks ----

    // ---- expands ----

    // ---- parent ----
    private final Macro parent;

    @Override
    public Macro get_parent() {

        return this.parent;
    }

    // ---- constructor ----
    M_expand_append_before_first_text_block(
            Macro parent,
            String p_text_block_name) {

        this.parent = parent;
        this.p_text_block_name = p_text_block_name;
    }

    // ---- local parameter accessors ----

    String get_local_p_text_block_name() {

        return this.p_text_block_name;
    }

    // ---- local text block accessors ----

    // ---- parameter accessors ----

    private String cached_p_text_block_name;

    String get_p_text_block_name() {

        String result = this.cached_p_text_block_name;
        if (result == null) {
            Macro current = this;
            while (!(current instanceof M_expand_append_before_first_text_block)) {
                current = current.get_parent();
            }
            result = ((M_expand_append_before_first_text_block) current)
                    .get_local_p_text_block_name();
            this.cached_p_text_block_name = result;
        }
        return result;
    }

    // ---- text block accessors ----

    // sub-macro creators

    // ---- append ----

    @Override
    public void appendTo(
            StringBuilder sb) {

        sb.append("          get_t_");
        sb.append(get_p_text_block_name());
        sb.append("().appendTo(sb);");
        sb.append(EOL);
    }
}
