/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.objectmacro.macro;

import java.util.LinkedList;
import java.util.List;

public class M_submacro_this
        extends Macro {

    // ---- constructor ----

    M_submacro_this(
            Macro parent) {

        this.parent = parent;
    }

    // ---- parent ----

    private final Macro parent;

    @Override
    Macro get_parent() {

        return this.parent;
    }

    // ---- expands ----

    private final List<Macro> e_expand_3 = new LinkedList<Macro>();

    // ---- macro creators ----

    public M_comma new_comma() {

        M_comma result = new M_comma();
        this.e_expand_3.add(result);
        return result;
    }

    // ---- appendTo ----

    @Override
    public void appendTo(
            StringBuilder sb) {

        sb.append("this");
        if (this.e_expand_3.size() == 0) {
        }
        else {
            boolean first = true;
            for (Macro macro : this.e_expand_3) {
                if (first) {
                    first = false;
                }
                else {
                }
                macro.appendTo(sb);
            }
        }
    }

}
