/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.objectmacro.macro;

public class M_submacro_comma
        extends Macro {

    // ---- EOL ----
    private static final String EOL = System.getProperty("line.separator");

    // ---- parameters ----

    // ---- text blocks ----

    // ---- expands ----

    // ---- parent ----
    private final Macro parent;

    @Override
    public Macro get_parent() {

        return this.parent;
    }

    // ---- constructor ----
    M_submacro_comma(
            Macro parent) {

        this.parent = parent;
    }

    // ---- local parameter accessors ----

    // ---- local text block accessors ----

    // ---- parameter accessors ----

    // ---- text block accessors ----

    private T_comma cached_t_comma;

    T_comma get_t_comma() {

        T_comma result = this.cached_t_comma;
        if (result == null) {
            result = T_comma.getInstance();
            this.cached_t_comma = result;
        }
        return result;
    }

    // sub-macro creators

    // ---- append ----

    @Override
    public void appendTo(
            StringBuilder sb) {

        get_t_comma().appendTo(sb);
    }
}
