/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.objectmacro.macro;

public class M_text_append
        extends Macro {

    // ---- constructor ----

    M_text_append(
            String p_text) {

        this.p_text = p_text;
    }

    // ---- parent ----

    @Override
    Macro get_parent() {

        return null;
    }

    // ---- parameters ----

    private final String p_text;

    String get_local_p_text() {

        return this.p_text;
    }

    // ---- parameter accessors ----

    private String cached_p_text;

    private String get_p_text() {

        String result = this.cached_p_text;

        if (result == null) {
            Macro current = this;

            while (!(current instanceof M_text_append)) {
                current = current.get_parent();
            }

            result = ((M_text_append) current).get_local_p_text();
            this.cached_p_text = result;
        }

        return result;
    }

    // ---- appendTo ----

    @Override
    public void appendTo(
            StringBuilder sb) {

        sb.append("    sb.append(\"");
        sb.append(get_p_text());
        sb.append("\");");
        sb.append(EOL);
    }

}
