/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.objectmacro.macro;

public class Macro_expand_instruction {

    // parameter declarations
    private final String param_expand_name;

    private final String param_indent;

    // nested macro declarations

    // constructor
    Macro_expand_instruction(
            String param_expand_name,
            String param_indent) {

        this.param_expand_name = param_expand_name;
        this.param_indent = param_indent;
    }

    // toString
    @Override
    public String toString() {

        StringBuilder sb = new StringBuilder();
        sb.append(this.param_indent);
        sb.append("    for(Macro vMacro : e");
        sb.append(this.param_expand_name);
        sb.append(") {");
        sb.append(System.getProperty("line.separator"));
        sb.append(this.param_indent);
        sb.append("      vMacro.appendTo(sb);");
        sb.append(System.getProperty("line.separator"));
        sb.append(this.param_indent);
        sb.append("    }");
        sb.append(System.getProperty("line.separator"));
        return sb.toString();
    }

    // nested macros

}
