/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.objectmacro.macro;

public class T_text_block_declaration_header
        extends Printable {

    // ---- EOL ----
    private static final String EOL = System.getProperty("line.separator");

    // ---- parent ----
    private final Macro parent;

    // ---- constructor ----
    T_text_block_declaration_header(
            Macro parent) {

        this.parent = parent;
    }

    // ---- parameter accessors ----

    // ---- text block accessors ----

    // ---- append ----

    @Override
    public void appendTo(
            StringBuilder sb) {

        sb.append("  // ---- text blocks ----");
        sb.append(EOL);
        sb.append(EOL);
    }
}
