/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.objectmacro.errormessage;

class CacheBuilder {

    private String expansion = null;

    public String getExpansion() {

        return this.expansion;
    }

    public void setExpansion(
            String expansion) {

        this.expansion = expansion;
    }
}
