#!/bin/bash

# This file is part of SableCC (http://sablecc.org/).
#
# See the NOTICE file distributed with this work for copyright information.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

rm -f src/org/sablecc/objectmacro/codegeneration/java/macro/*.java
rm -f src/org/sablecc/objectmacro/codegeneration/scala/macro/*.java
rm -f src/org/sablecc/objectmacro/codegeneration/c/macro/*.java
rm -f src/org/sablecc/objectmacro/codegeneration/intermediate/macro/*.java
rm -f src/org/sablecc/objectmacro/errormessage/*.java

rm -f src/org/sablecc/sablecc/codegeneration/java/macro/*.java
rm -f src/org/sablecc/sablecc/launcher/errormessage/*.java
rm -f src/org/sablecc/sablecc/semantics/errormessage/*.java

java -jar lib/objectmacro.jar -d src -p org.sablecc.objectmacro.codegeneration.java.macro macros/objectmacro-java.objectmacro
java -jar lib/objectmacro.jar -d src -p org.sablecc.objectmacro.codegeneration.scala.macro macros/objectmacro-scala.objectmacro
java -jar lib/objectmacro.jar -d src -p org.sablecc.objectmacro.codegeneration.c.macro macros/objectmacro-c.objectmacro
java -jar lib/objectmacro.jar -d src -p org.sablecc.objectmacro.codegeneration.intermediate.macro macros/objectmacro-intermediate.objectmacro
java -jar lib/objectmacro.jar -d src -p org.sablecc.objectmacro.errormessage macros/objectmacro-errormessage.objectmacro

java -jar lib/objectmacro.jar -d src -p org.sablecc.sablecc.codegeneration.java.macro macros/sablecc-java.objectmacro
java -jar lib/objectmacro.jar -d src -p org.sablecc.sablecc.launcher.errormessage macros/sablecc-launcher-errormessage.objectmacro
java -jar lib/objectmacro.jar -d src -p org.sablecc.sablecc.semantics.errormessage macros/sablecc-semantics-errormessage.objectmacro
