#!/bin/bash

# This file is part of SableCC (http://sablecc.org/).
#
# See the NOTICE file distributed with this work for copyright information.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

java -jar lib/objectmacro.jar -d tests/objectmacro/intermediate/ tests/objectmacro/common/accepted/test.objectmacro
java -jar lib/objectmacro.jar -d tests/objectmacro/intermediate/ tests/objectmacro/common/refused/cyclic_reference.objectmacro
java -jar lib/objectmacro.jar -d tests/objectmacro/intermediate/ tests/objectmacro/common/refused/test1.objectmacro
java -jar lib/objectmacro.jar -d tests/objectmacro/intermediate/ tests/objectmacro/common/refused/test2.objectmacro

java -jar lib/objectmacro.jar -d tests/objectmacro/intermediate/ tests/objectmacro/common/jpa_entity.objectmacro
java -jar lib/objectmacro-back.jar -d tests/objectmacro/java -p entity tests/objectmacro/intermediate/jpa_entity.intermediate


