#!/bin/bash

# This file is part of SableCC ( http://sablecc.org ).
#
# See the NOTICE file distributed with this work for copyright information.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This program is used to perform regression tests.

SABLECCJAR=../lib/sablecc.jar

java -jar "$SABLECCJAR" --version >/dev/null || exit

mkdir alt out 2>/dev/null

if test "x$#" = "x0"
then
        echo usage: `basename $0` [-v] grammar-files*
        exit
fi


verbose=false
stop=false
while [ $stop = false ]; do
        case $1 in
                -v) verbose=true; shift;;
                *) stop=true
        esac
done

differ() {
        r="$1"
        if test \! -f "sav/$r"
        then
                if test -s "out/$r"
                then
                        echo "[***no sav***] cp 'out/$r' sav/"
                        test $verbose = true && { cat "out/$r" ; echo ; }
                else
                        echo "[0K]"
                fi
        elif diff "sav/$r" "out/$r" >/dev/null
        then
                echo "[OK]"
        else
                echo "[******failed******] diff 'sav/$r' 'out/$r'"
                test $verbose = true && { diff "sav/$r" "out/$r" ; echo ; }
        fi
}


for f in "$@"
do
        for a in "$f" `./alterner.pl $f`
        do
                cla=""
                echo -n "* $a: "
                res=`basename "$a" .sablecc`.res
                java -jar "$SABLECCJAR" --quiet --destination="src/$res" "$a" >"out/$res" 2>&1
                if test $? != 0
                then
                        echo -n "!scc "
                else
                        echo -n ". "
                        jc=`cd "src/$res"; ls */Tester.java`
                        js=`ls "src/$res"/*/Tester.java`
                        javac -sourcepath "src/$res" "$js" #2>/dev/null
                        if test $? != 0
                        then
                                echo -n "!javac "
                        else
                                echo -n ". "
                                cla=${jc%.java}
                        fi
                fi

                differ $res

                if test \! -z $cla
                then
                        bf=`basename "$f" .sablecc`
                        for i in "$bf".input*
                        do
                                test -f $i || { echo "   - no input: $i" ; continue ; }
                                ni=${i#$bf}
                                resi=`basename "$a" .sablecc`"$ni".res
                                echo -n "  - $i: "
                                java -cp "src/$res" "$cla" "$i" > "out/$resi"
                                if test $? != 0
                                then
                                        echo -n "!java "
                                else
                                        echo -n ". "
                                fi

                                differ "$resi"
                        done
                fi
        done
done
