/* This file was generated by SableCC's ObjectMacro. */

package org.test.test;

import java.util.*;

public class MHello extends Macro{

    private String field_Nom;


    public MHello(String pNom){

        this.setPNom(pNom);


    }

    private void setPNom( String pNom ){
        if(pNom == null){
            throw ObjectMacroException.parameterNull("Nom");
        }

        this.field_Nom = pNom;
    }

    private String buildNom(){

        return this.field_Nom;
    }

    private String getNom(){

        return this.field_Nom;
    }


    @Override
    void apply(
            InternalsInitializer internalsInitializer){

        internalsInitializer.setHello(this);
    }

   @Override
    public String build(){

        BuildState buildState = this.build_state;

        if(buildState == null){
            buildState = new BuildState();
        }
        else if(buildState.getExpansion() == null){
            throw ObjectMacroException.cyclicReference("Hello");
        }
        else{
            return buildState.getExpansion();
        }
        this.build_state = buildState;

        

        

        StringBuilder sb0 = new StringBuilder();

        sb0.append("    Bonjour ");
        sb0.append(buildNom());
        sb0.append(", ce code est genere a partir d'un patron ObjectMacro2 !;");

        buildState.setExpansion(sb0.toString());
        return sb0.toString();
    }

    @Override
    String build(Context context) {
        return build();
    }
}