/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.objectmacro.codegeneration.c.macro;

public class MAncestorParam {

    private final String pName;

    private final MAncestorParam mAncestorParam = this;

    MAncestorParam(
            String pName) {

        if (pName == null) {
            throw new NullPointerException();
        }
        this.pName = pName;
    }

    String pName() {

        return this.pName;
    }

    private String rName() {

        return this.mAncestorParam.pName();
    }

    @Override
    public String toString() {

        StringBuilder sb = new StringBuilder();
        sb.append("struct M");
        sb.append(rName());
        sb.append("* m");
        sb.append(rName());
        return sb.toString();
    }

}
