/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.objectmacro.codegeneration.c.macro;

public class MEolPart {

    MEolPart() {

    }

    @Override
    public String toString() {

        StringBuilder sb = new StringBuilder();
        sb.append("  sizeString += List_pushback(listString, strdup(\"\\n\"));");
        sb.append(System.getProperty("line.separator"));
        return sb.toString();
    }

}
