/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.objectmacro.codegeneration.c.macro;

public class MInclude {

    private final String pPname;

    private final MInclude mInclude = this;

    MInclude(
            String pPname) {

        if (pPname == null) {
            throw new NullPointerException();
        }
        this.pPname = pPname;
    }

    String pPname() {

        return this.pPname;
    }

    private String rPname() {

        return this.mInclude.pPname();
    }

    @Override
    public String toString() {

        StringBuilder sb = new StringBuilder();
        sb.append("#include \"M");
        sb.append(rPname());
        sb.append(".h\"");
        sb.append(System.getProperty("line.separator"));
        return sb.toString();
    }

}
