/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.objectmacro.codegeneration.c.macro;

public class MInlineEol {

    MInlineEol() {

    }

    @Override
    public String toString() {

        StringBuilder sb = new StringBuilder();
        sb.append("\"\\n\"");
        return sb.toString();
    }

}
