/* This file was generated by SableCC's ObjectMacro. */

package org.sablecc.objectmacro.codegeneration.c.macro;

public class MParamInsert {

    private final String pPname;

    private final MParamInsert mParamInsert = this;

    MParamInsert(
            String pPname) {

        if (pPname == null) {
            throw new NullPointerException();
        }
        this.pPname = pPname;
    }

    String pPname() {

        return this.pPname;
    }

    private String rPname() {

        return this.mParamInsert.pPname();
    }

    @Override
    public String toString() {

        StringBuilder sb = new StringBuilder();
        sb.append("r");
        sb.append(rPname());
        sb.append("()");
        return sb.toString();
    }

}
